project_id = "ujguqvyshjnrxnmsvsdf"

[functions.telegram-listener]
verify_jwt = false

[functions.telegram-channel-reader]
verify_jwt = false

[functions.pocket-option-trade]
verify_jwt = false

[functions.telegram-fast-poller]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-webhook-setup]
verify_jwt = false

[functions.analyze-chart-image]
verify_jwt = false

[functions.analyze-mt5-chart]
verify_jwt = false